spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: notification-service
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8088
