apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ticketing
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ticketbooking/user-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: ticket-config
            - secretRef:
                name: ticket-secret
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/userdb"
          resources:
            requests:
              cpu: "100m"
              memory: "384Mi"
            limits:
              memory: "768Mi"
          startupProbe:
            tcpSocket:
              port: 8081
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 8081
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ticketing
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
