spring:
  application:
    name: admin-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/admindb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8089
